version: "3"

services:
  test-psql:
    container_name: test-psql
    image: postgres:11.1
    volumes:
      - test-psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: test
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    restart: always

volumes:
  test-psql-data: